application/models/__init__.py
from .models import db, User, Article

application/models/models.py
from flask_sqlalchemy import SQLAlchemy
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from datetime import datetime

db = SQLAlchemy()


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(25), unique=True)
    pwdhash = db.Column(db.String(100))

    def __init__(self, username, password):
        self.username = username
        self.set_password(password)

    def set_password(self, password):
        self.pwdhash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.pwdhash, password)


class Article(db.Model):
    __tablename__ = 'article'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100))
    descp = db.Column(db.String(100))
    content = db.Column(db.String(10000))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    user = db.relationship('User', backref=db.backref('article'))
    time = db.Column(db.DateTime, default=datetime.now)
    category = db.Column(db.String(10))
    thumbnail = db.Column(db.String(50))
    likes = db.Column(db.Integer, default=0)

    def __init__(self, title, descp, content, category, thumbnail):
        self.title = title
        self.content = content
        self.descp = descp
        self.category = category
        self.thumbnail = thumbnail

application/forms.py
# coding: utf-8
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Email, Length


class LoginForm(FlaskForm):
    username = StringField('用户名', validators=[DataRequired('请输入用户名！')])
    password = PasswordField('密码', validators=[DataRequired('请输入密码！')])
    login = SubmitField('登陆')


class PublishForm(FlaskForm):
    title = StringField('标题', validators=[DataRequired('请输入标题！'), Length(max=50, message='标题最长为50位')],
                        render_kw={"placeholder": "标题"})
    descp = TextAreaField('简介', validators=[DataRequired('请输入简介！'), Length(max=150, message='简介最长为150位')],
                          render_kw={"placeholder": "简介"})
    content = TextAreaField('正文', validators=[DataRequired('请输入正文！'), Length(max=10000, message='正文最长为10000位')],
                            render_kw={"placeholder": "正文"})
    publish = SubmitField('发表')

application/__init__.py
from .app import create_app
from .models import db

application/app.py
# coding: utf-8
from flask import Flask
from flask_login import LoginManager
from .models import db, User
from .controllers import bp
from .configs import config


def create_app(config_name=None):
    """Create Flask app object based on environments.
    :param config_name: string, allowed value: default/development/production.
    :return: Flask app object.
    """
    if config_name is None:
        config_name = 'default'

    # create flask app
    app = Flask(__name__)
    app.config.from_object(config[config_name])

    # init db models
    db.init_app(app)

    # init login manager with app
    login_manager = LoginManager()
    login_manager.session_protection = 'strong'
    login_manager.login_view = "blog.login"
    login_manager.login_message = "该页面需要登陆"
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    # blueprints
    app.register_blueprint(bp)

    return app

application/controllers/__init__.py
from .routes import bp

application/controllers/routes.py
# coding: utf-8
from flask import Blueprint, render_template, redirect, url_for, request, session, flash, make_response, current_app, jsonify
from flask_login import login_required, current_user, login_user, logout_user
from ..forms import LoginForm, PublishForm
from application.models import db, User, Article
from sqlalchemy import desc, or_
import os
import random
import datetime

# If Python2, import sys and set encoding utf-8, else ignore.
try:
    import sys
    reload(sys)
    sys.setdefaultencoding('utf8')
except NameError:
    pass


basedir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
bp = Blueprint(
    'blog',
    __name__,
    template_folder='../templates'
)


@bp.before_request
def make_session_permant():
    """Make session permanent to avoid flask expires the session once close
    the browser. To limit permanent session lifetime, please go to
    configs.py and set variable PERMANENT_SESSION_LIFETIME.
    """
    session.permanent = True


@bp.route('/')
def home():
    """Home page route for the web site. This func will first order articles
    based on likes and select top 5 to list.
    :return: render the home page with query result.
    """
    feat_articles = Article.query.order_by(desc(Article.likes)).limit(5).all()
    return render_template('home.html', feat_articles=feat_articles)


@bp.route('/login', methods=['GET', 'POST'])
def login():
    """
    Login route for admin to login to system.
    :return: redirect to home page if a success login, else it will render the
             page with error messages.
    """
    if current_user.is_authenticated:
        return redirect(url_for('blog.home'))
    form = LoginForm()
    if request.method == 'POST':
        if not form.validate():
            return render_template('login.html', form=form)
        username = form.username.data
        password = form.password.data
        user = User.query.filter_by(username=username).first()
        if user is not None and user.check_password(password):
            login_user(user)
            return redirect(session.get('next') or url_for('blog.home'))
        else:
            flash('用户名或密码不正确！')
            return render_template('login.html', form=form)
    elif request.method == 'GET':
        session['next'] = request.args.get('next')
        return render_template('login.html', form=form)


@bp.route('/logout')
def logout():
    """Logout the current user.
    :return: redirect to home page.
    """
    logout_user()
    return redirect(url_for('blog.home'))


@bp.route('/articles/page/<int:page>')
def articles(page=1):
    """Paginate and list articles by requested page number
    :param page: integer type, the page number to show.
    :return: render articles.html.
    """
    articles = Article.query.order_by(desc(Article.time)).paginate(
                page, current_app.config['PER_PAGE'], error_out=False)
    return render_template('article.html', articles=articles, count=articles.total)


@bp.route('/article/<int:id>')
def details(id):
    """Show contents of an article.
    :param id: article id.
    :return: render contents if id exists, else render 404 page.
    """
    details = Article.query.filter_by(id=id).first()
    if details is not None:
        return render_template('details.html', details=details)
    else:
        return render_template('404.html')


@bp.route('/category/<category>/page/<int:page>')
def category(category, page=1):
    """Return articles under certain category.
    :param category: article category.
    :param page: integer type, page number.
    :return: render category.html
    """
    result = Article.query.filter_by(category=category).order_by(desc(Article.time)).paginate(
                page, current_app.config['PER_PAGE'], error_out=False)
    return render_template('category.html', result=result, category=category)


@bp.route('/publish', methods=['GET', 'POST'])
@login_required
def publish():
    """Publish an article with CKEditor integrated.
    :return: redirect to all articles page if a success publish, else render
    the template with error messages.
    """
    form = PublishForm()
    if request.method == 'POST':
        if not form.validate():
            return render_template('publish.html', form=form)
        title = form.title.data
        descp = form.descp.data
        content = form.content.data
        category = request.form.get('radio')
        thumbnail = request.files.get('thumbnail')
        if thumbnail is None or thumbnail.filename == '':
            thumb_url = ''
        else:
            # upload thumbnail images
            fname, fext = os.path.splitext(thumbnail.filename)
            if fext.rsplit('.')[1] not in current_app.config['ALLOWED_EXTENSIONS']:
                flash('请上传png,jpg或者gif格式图片！')
                return render_template('publish.html', form=form)
            rnd_name = '%s%s' % (gen_rnd_filename(), fext)
            filepath = os.path.join(basedir, 'static', 'img', 'thumbnail', rnd_name)
            thumbnail.save(filepath)
            thumb_url = url_for('static', filename='%s/%s/%s' % ('img', 'thumbnail', rnd_name))
        new_article = Article(title, descp, content, category, thumb_url)
        db.session.add(new_article)
        db.session.commit()
        return redirect(url_for('blog.articles', page=1))
    elif request.method == 'GET':
        return render_template('publish.html', form=form)


@bp.route('/error/413')
def file_too_large():
    """This is for nginx error code 413. If thumbnail image size is larger than
    the limitation, nginx will redirect to this route.
    :return: render 413.html.
    """
    return render_template('413.html')


@bp.route('/manage')
@login_required
def manage():
    """Admin management interface. Admin can publish, delete and view
    information for the articles.
    :return: render template manage.html.
    """
    articles = Article.query.order_by(desc(Article.time)).all()
    return render_template('manage.html', articles=articles)


@bp.route('/delete', methods=['POST'])
@login_required
def delete():
    """Delete requested articles. This will receive POST request from manage
    interface(using jQuery ajax), and delete articles based on form parameter
    'ids'.
    :return: redirect to manage page with flash messages.
    """
    ids = request.form.get('ids')
    filter_args = (Article.id == int(i) for i in ids.split(','))
    result = Article.query.filter(or_(filter_args)).delete()
    db.session.commit()
    if result > 0:
        flash('{0}篇文章已删除'.format(str(result)))
        return redirect(url_for('blog.manage'))
    else:
        flash('所选文章不存在或已删除'.format(str(result)))
        return redirect(url_for('blog.manage'))


@bp.route('/like_article')
def like_article():
    """ Like an article. This route is used by jQuery ajax function in article
    details page.
    :return: return json object with success value(1 if success else 0).
    """
    id = request.args.get('id')
    if id is not None:
        article = Article.query.filter_by(id=int(id)).first()
        article.likes = Article.likes + 1
        db.session.commit()
        return jsonify({'success': 1})
    else:
        return jsonify({'success': 0})


@bp.route('/searching')
def searching():
    """Search keyword render page. This route will show search result which jQuery
    ajax call gets.
    :return: render page if keyword is not None, else redirect to home page.
    """
    keyword = request.args.get('keyword')
    if keyword is not None:
        return render_template('search.html', keyword=keyword)
    else:
        return redirect(url_for('blog.home'))


@bp.route('/search')
def search():
    """Search keyword from database. This is the method which jQuery ajax
    will call. The return object will be rendered in search keyword page.
    :return: render result.html with query result.
    """
    keyword = request.args.get('keyword')
    # simulate time taken job
    # time.sleep(1)
    result = Article.query.filter(Article.content.contains(keyword)).all()
    if len(result) == 0:
        result.extend(Article.query.filter(Article.title.contains(keyword)).all())
    return render_template('result.html', result=result, keyword=keyword)


def gen_rnd_filename():
    """Generate random filename based on current time.
    :return:
    """
    filename_prefix = datetime.datetime.now().strftime('%Y%m%d%H%M%S')
    return '%s%s' % (filename_prefix, str(random.randrange(1000, 10000)))


@bp.route('/ckupload/', methods=['POST'])
def ckupload():
    """CKEditor image upload. CKEditor will call this method when uploading
    a image. The URL is defined in publish page('filebrowserUploadUrl').
    """
    error = ''
    url = ''
    callback = request.args.get("CKEditorFuncNum")
    if request.method == 'POST' and 'upload' in request.files:
        fileobj = request.files['upload']
        fname, fext = os.path.splitext(fileobj.filename)
        rnd_name = '%s%s' % (gen_rnd_filename(), fext)
        filepath = os.path.join(basedir, 'static', 'img', 'article', rnd_name)
        # check if path exists, if not create it
        dirname = os.path.dirname(filepath)
        if not os.path.exists(dirname):
            try:
                os.makedirs(dirname)
            except:
                error = 'ERROR_CREATE_DIR'
        elif not os.access(dirname, os.W_OK):
            error = 'ERROR_DIR_NOT_WRITEABLE'
        if not error:
            fileobj.save(filepath)
            url = url_for('static', filename='%s/%s/%s' % ('img', 'article', rnd_name))
    else:
        error = 'post error'
    res = """
<script type="text/javascript">
  window.parent.CKEDITOR.tools.callFunction(%s, '%s', '%s');
</script>

""" % (callback, url, error)
    response = make_response(res)
    response.headers["Content-Type"] = "text/html"
    return response


@bp.route('/about')
def about():
    return render_template('about.html')


@bp.route('/video')
def video():
    """Video page.

application/templates/413.html
{% extends "base.html" %}

{% block head %}
{{ super() }}
<script src="{{ url_for('static', filename='js/jquery-3.3.1.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/goBack.js') }}"></script>
{% endblock %}

{% block title %}413 - 图片超出大小限制{% endblock %}
{% block content %}
<div class="uk-container uk-container-small uk-margin-top">
    <p class="uk-text-lead">图片超出最大2M限制，请重新上传！</p>
    <button id="go-back" class="uk-button uk-button-danger uk-button-small uk-margin-top" type="button">返回发布页面</button>
</div>
{% endblock %}

application/templates/article.html
{% extends "base.html" %}

{% block head %}
{{ super() }}
{% endblock %}

{% block title %}文章{% endblock %}
{% block content %}

{% if articles.page == 1 %}
<div class="uk-container uk-container-small uk-margin-top">
    <p class="uk-text-lead uk-text-muted">共有{{ count }}篇文章。</p>
</div>
{% endif %}

{% for a in articles.items %}
<div class="uk-container uk-container-small uk-margin-top article-background uk-box-shadow-medium uk-box-shadow-hover-xlarge">
    <article class="uk-comment">
        <header class="uk-comment-header uk-grid-medium uk-flex-middle" uk-grid>
            <div class="uk-width-auto uk-margin-top">
                <a href="{{ url_for('blog.details', id=a.id) }}" class="">
                    <img class="uk-comment-avatar" src="{{ a.thumbnail|default(url_for('static', filename='img/thumbnail/default.jpg'), true) }}" width="80" height="80" alt="">
                </a>
            </div>
            <div class="uk-width-expand uk-margin-top">
                <h4 class="uk-comment-title uk-margin-remove"><a class="uk-link-heading" href="{{ url_for('blog.details', id=a.id) }}">{{ a.title }}</a></h4>
                <p class="uk-comment-meta article-date">
                    {{ a.time.strftime('%Y{y}%m{m}%d{d} %H:%M').format(y='年', m='月', d='日') }}
                    <a href="{{ url_for('blog.category', category=a.category, page=1) }}" class="uk-link-reset"><span uk-icon="icon: folder" class="uk-icon uk-margin-left"></span>
                    {{ a.category }}
                    </a>
                    <a href="{{ url_for('blog.details', id=a.id) }}" class="uk-link-reset"><span uk-icon="icon: heart" class="uk-icon uk-margin-left"></span>
                    {{ a.likes }}
                    </a>
                </p>
            </div>
        </header>
        <div class="uk-comment-body uk-margin-bottom">
            <p>{{ a.descp }}</p>
        </div>
    </article>
</div>
{% endfor %}

<div class="uk-container uk-container-small uk-margin-large-top uk-margin-xlarge-bottom">
    <ul class="uk-pagination uk-flex-center" uk-margin>
        {% if articles.has_prev %}
        <li><a href="{{ url_for('blog.articles', page=articles.prev_num) }}"><span uk-pagination-previous></span></a></li>
        {% else %}
        <li class="uk-disabled"><a href="#"><span uk-pagination-previous></span></a></li>
        {% endif %}

        {% for i in range(articles.pages) %}
            {% if articles.page == i+1 %}
                <li class="uk-active"><span>{{ i+1 }}</span></li>
            {% else %}
                <li><a href="{{ url_for('blog.articles', page=i+1) }}">{{ i+1 }}</a></li>
            {% endif %}
        {% endfor %}

        {% if articles.has_next %}
        <li><a href="{{ url_for('blog.articles', page=articles.next_num) }}"><span uk-pagination-next></span></a></li>
        {% else %}
        <li class="uk-disabled"><a href="#"><span uk-pagination-next></span></a></li>
        {% endif %}

    </ul>
</div>

{% endblock %}

application/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        {% block head %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/uikit.min.css') }}" />
        <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}" />
        <link rel="icon" href="{{ url_for('static', filename = 'img/favicon.ico') }}" type="image/x-icon">
        <script src="{{ url_for('static', filename='js/uikit.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/uikit-icons.min.js') }}"></script>
        {% endblock %}
    </head>

    <title>{% block title %}{% endblock %} - My learn and earn </title>

    <body>

        <nav class="uk-navbar uk-navbar-container uk-margin">
            <div class="uk-navbar-left">
                <a class="uk-navbar-item uk-logo" href="{{ url_for('blog.home') }}" title="首页"><img width="50" src="{{ url_for('static', filename='img/logo.png') }}"></a>
                <ul class="uk-navbar-nav">
                    <li class="uk-active"><a href="{{ url_for('blog.home') }}" class="menu-text">首页</a></li>
                    <li><a href="{{ url_for('blog.articles', page=1) }}">文章</a></li>
                    <li><a href="{{ url_for('blog.about') }}">关于</a></li>
                </ul>
            </div>

            <div class="uk-navbar-right">

                <div>
                    <a class="uk-navbar-toggle" uk-search-icon href="#"></a>
                    <div class="uk-drop" uk-drop="mode: click; pos: left-center; offset: 0">
                        <form class="uk-search uk-search-navbar uk-width-1-1" id="search" method="GET" action="{{ url_for('blog.searching') }}">
                            <input class="uk-search-input" name="keyword" type="search" placeholder="Search..." autofocus>
                        </form>
                    </div>
                </div>

                <a class="uk-navbar-toggle menu-text" uk-toggle="target: #offcanvas-nav-primary">
                    <span uk-navbar-toggle-icon></span> <span class="uk-margin-small-left">菜单</span>
                </a>

            </div>

        </nav>



        {% block content %}
        {% endblock %}

        <div class="uk-offcanvas-content">

            <div id="offcanvas-nav-primary" uk-offcanvas="overlay: false">
                <div class="uk-offcanvas-bar uk-flex uk-flex-column">

                    <ul class="uk-nav uk-nav-primary uk-nav-center uk-margin-auto-vertical">
                        <li class="uk-active">
                            <a href="{{ url_for('blog.home') }}"><span class="uk-margin-small-right" uk-icon="icon: home"></span> 首页</a>
                        </li>
                        <!-- <li class="uk-nav-header">Header</li> -->
                        <li><a href="{{ url_for('blog.articles', page=1) }}"><span class="uk-margin-small-right" uk-icon="icon: list"></span> 文章</a></li>
                        <li><a href="{{ url_for('blog.about') }}"><span class="uk-margin-small-right" uk-icon="icon: user"></span> 关于</a></li>
                        <!--<li><a href="{{ url_for('blog.video') }}"><span class="uk-margin-small-right" uk-icon="icon: play-circle"></span> 视频 </a></li>-->
                        {% if not current_user.is_authenticated %}
                        <li class="uk-parent">
                            <a href="{{ url_for('blog.login') }}"><span class="uk-margin-small-right" uk-icon="icon: sign-in"></span> 登录</a>
                        </li>
                        {% endif %}

                        {% if current_user.is_authenticated %}
                        <li class="uk-nav-divider"></li>
                        <li><a href="{{ url_for('blog.publish') }}"><span class="uk-margin-small-right" uk-icon="icon: file-edit"></span> 发表</a></li>
                        <li><a href="{{ url_for('blog.manage') }}"><span class="uk-margin-small-right" uk-icon="icon: settings"></span> 管理</a></li>
                        <li><a href="{{ url_for('blog.logout') }}"><span class="uk-margin-small-right" uk-icon="icon: trash"></span> 退出</a></li>
                        {% endif %}
                    </ul>

                </div>
            </div>
        </div>

        <div class="uk-container uk-container-expand uk-text-center uk-margin-xlarge-top footer">
            <ul uk-margin="" class="uk-subnav tm-subnav uk-flex-inline uk-flex-center uk-margin-remove-bottom">
                <li><a href="mailto:myheartsgoon@gmail.com">
                    <span uk-icon="icon: mail" class="uk-margin-small-right uk-icon"></span>联系我</a>
                </li>
                <li><a href="https://github.com/myheartsgoon/my-learn-and-earn">
                    <span uk-icon="icon: github" class="uk-margin-small-right uk-icon"></span>GitHub</a>
                </li>
                <li><a href="{{ url_for('blog.about') }}">
                    <span uk-icon="icon: user" class="uk-margin-small-right uk-icon"></span>关于</a>
                </li>
            </ul>
        </div>
    </body>
</html>

application/templates/category.html
{% extends "base.html" %}

{% block head %}
{{ super() }}
{% endblock %}

{% block title %}{{ category }}{% endblock %}
{% block content %}
<div class="uk-container uk-container-small uk-margin-top">
    <h3>文章分类 - <span class="uk-text-bold">{{ category }}</span></h3>
</div>

{% for a in result.items %}
<div class="uk-container uk-container-small uk-margin-top article-background uk-box-shadow-medium uk-box-shadow-hover-xlarge">
    <article class="uk-comment">
        <header class="uk-comment-header uk-grid-medium uk-flex-middle" uk-grid>
            <div class="uk-width-auto uk-margin-top">
                <a href="{{ url_for('blog.details', id=a.id) }}" class="">
                    <img class="uk-comment-avatar" src="{{ a.thumbnail|default(url_for('static', filename='img/thumbnail/default.jpg'), true) }}" width="80" height="80" alt="">
                </a>
            </div>
            <div class="uk-width-expand uk-margin-top">
                <h4 class="uk-comment-title uk-margin-remove"><a class="uk-link-heading" href="{{ url_for('blog.details', id=a.id) }}">{{ a.title }}</a></h4>
                <p class="uk-comment-meta article-date">
                    {{ a.time.strftime('%Y{y}%m{m}%d{d} %H:%M').format(y='年', m='月', d='日') }}
                    <a href="{{ url_for('blog.category', category=a.category, page=1) }}" class="uk-link-reset"><span uk-icon="icon: folder" class="uk-icon uk-margin-left"></span>
                    {{ a.category }}
                    </a>
                </p>
            </div>
        </header>
        <div class="uk-comment-body uk-margin-bottom">
            <p>{{ a.descp }}</p>
        </div>
    </article>
</div>
{% endfor %}

<div class="uk-container uk-container-small uk-margin-large-top uk-margin-xlarge-bottom">
    <ul class="uk-pagination uk-flex-center" uk-margin>
        {% if result.has_prev %}
        <li><a href="{{ url_for('blog.category', category=category, page=result.prev_num) }}"><span uk-pagination-previous></span></a></li>
        {% else %}
        <li class="uk-disabled"><a href="#"><span uk-pagination-previous></span></a></li>
        {% endif %}

        {% for i in range(result.pages) %}
            {% if result.page == i+1 %}
                <li class="uk-active"><span>{{ i+1 }}</span></li>
            {% else %}
                <li><a href="{{ url_for('blog.category', category=category, page=i+1) }}">{{ i+1 }}</a></li>
            {% endif %}
        {% endfor %}

        {% if result.has_next %}
        <li><a href="{{ url_for('blog.category', category=category, page=result.next_num) }}"><span uk-pagination-next></span></a></li>
        {% else %}
        <li class="uk-disabled"><a href="#"><span uk-pagination-next></span></a></li>
        {% endif %}

    </ul>
</div>

{% endblock %}

application/templates/manage.html
{% extends "base.html" %}

{% block head %}
{{ super() }}
<script src="{{ url_for('static', filename='js/jquery-3.3.1.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/manage.js') }}"></script>
{% endblock %}

{% block title %}管理{% endblock %}
{% block content %}
<div class="uk-container uk-container-small uk-margin-top uk-margin-xlarge-bottom article-background">
    <ul class="uk-margin-top uk-text-bold" uk-tab>
        <li><a class="tab-size" href="#">文章管理</a></li>
        <li><a class="tab-size" href="#">个人介绍</a></li>
      </ul>
    <ul class="uk-switcher uk-margin">
        <li>
            <a id="new" class="uk-button uk-button-primary uk-button-small uk-margin-top" href="{{ url_for('blog.publish') }}" type="button">新增</a>
            <button id="delete" class="uk-button uk-button-danger uk-button-small uk-margin-top" type="button">删除</button>
            <input class="uk-input uk-form-width-medium uk-form-small uk-margin-top searchFilter" type="text" placeholder="搜索..">
            {% if get_flashed_messages() %}
            <div class="uk-alert-success" uk-alert>
                {% for message in get_flashed_messages() %}
                    <a class="uk-alert-close" uk-close></a>
                    <p>{{ message }}</p>
                {% endfor %}
            </div>
            {% endif %}

            <table class="uk-table uk-table-hover uk-table-divider searchable">
                <thead>
                    <tr>
                        <th><label><input class="uk-checkbox uk-margin-medium-right" type="checkbox" id="checkAll">  </label>  标题</th>
                        <th>描述</th>
                    </tr>
                </thead>
                <tbody>
                {% for a in articles %}
                    <tr>
                        <td><label><input class="uk-checkbox uk-margin-medium-right" type="checkbox" id="{{ a.id }}"></label><a href="{{ url_for('blog.details', id=a.id) }}" target="_blank" class="uk-link-heading">{{ a.title }}</a></td>
                        <td class="comment more">{{ a.descp }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <form id="action_form" action="{{ url_for('blog.delete') }}" method="POST" style="display: none">
                <input id="ids" name="ids" type="hidden">
            </form>
        </li>
    </ul>
</div>
{% endblock %}

application/templates/result.html
{% block content %}

{% if result|length == 0 %}
<div class="uk-container uk-container-small uk-margin-top">
    <p class="uk-text-lead uk-text-muted">没有找到相关结果</p>
</div>
{% endif %}

{% for r in result %}
<div class="uk-container uk-container-small uk-margin-top article-background uk-box-shadow-medium uk-box-shadow-hover-xlarge">
    <article class="uk-comment">
        <header class="uk-comment-header uk-grid-medium uk-flex-middle" uk-grid>
            <div class="uk-width-auto uk-margin-top">
                <a href="{{ url_for('blog.details', id=r.id) }}" class="">
                    <img class="uk-comment-avatar" src="{{ r.thumbnail|default(url_for('static', filename='img/thumbnail/default.jpg'), true) }}" width="80" height="80" alt="">
                </a>
            </div>
            <div class="uk-width-expand uk-margin-top">
                <h4 class="uk-comment-title uk-margin-remove"><a class="uk-link-heading" href="{{ url_for('blog.details', id=r.id) }}">{{ r.title }}</a></h4>
                <p class="uk-comment-meta article-date">
                    {{ r.time.strftime('%Y{y}%m{m}%d{d} %H:%M').format(y='年', m='月', d='日') }}
                    <a href="{{ url_for('blog.category', category=r.category, page=1) }}" class="uk-link-reset"><span uk-icon="icon: tag" class="uk-icon uk-margin-left"></span>
                    {{ r.category }}
                    </a>
                </p>
            </div>
        </header>
        <div class="uk-comment-body uk-margin-bottom">
            <p>{{ r.descp }}</p>
        </div>
    </article>
</div>
{% endfor %}
{% endblock %}

application/templates/search.html
{% extends "base.html" %}

{% block head %}
{{ super() }}
<script src="{{ url_for('static', filename='js/jquery-3.3.1.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/search.js') }}"></script>
{% endblock %}

{% block title %}搜索{% endblock %}
{% block content %}
<div class="uk-container uk-container-small uk-margin-top">
    <h3>正在搜索包含 "<a id="keyword" class="uk-link-reset uk-text-bold">{{ keyword }}</a>" 的文章...</h3>
</div>
<div id="container">
    <div class="uk-container uk-container-small uk-margin-top uk-position-center">
        <span class="uk-margin-small-right" uk-spinner="ratio: 3"></span>
    </div>
</div>

{% endblock %}